/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PeptideVisualization;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author taniyapal
 */
public class PeptidePanel extends javax.swing.JPanel {

    /**
     * Creates new form PeptidePanel
     */
    public PeptidePanel() {
        initComponents();
        start = new int[1000];
        stop = new int[1000];
        start[0] = 0;
        stop[0] = 0;
        reference = 0;
        counter = 0;
    }
    
    private int[] start;
    private int[] stop;
    private int reference;
    private int counter;
    public void addPositions(int startPos, int stopPos, int length) {
        if(startPos<0 || stopPos>length)
            return;
        if(start==null) {
            //start = new int[length];
            //stop = new int[length];
        }
        start[counter] = startPos;
        stop[counter] = stopPos;
        reference = length;
        counter++;
        if(start.length!=stop.length)
            System.out.println("Try again!!!");
        //
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.BLACK);
        g.drawRect(40, 40, 300,35);
        //MyFrame.
        
        //g.fillRect(60, 40, 15, 35);
        //g.fillRect(100,40, 15,35);
        //g.fillRect(180, 40, 15, 35);
        //g.fillRect(210,40,15,35);
        //g.fillRect(220,40,15,35);
        //g.fillRect(280,40,15,35);
        for(int i=0;i<start.length;i++) {
            g.fillRect(start[i], 40, stop[i]-start[i], 35);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
